### ISSUE TITLE
Killing the window in i3 stops the spirit

### ISSUE THREAD

**Issue by namelivia** [antony-jr/spirit#1]
I'm using i3, and let's say I have 3 terminals open, as soon as I kill one of them with Ctrl+D the spirit execution stops.
Here is a video, it is easier to see here:

https://user-images.githubusercontent.com/1571416/225988853-8dd831ed-496c-4acc-87dc-da92cb05ebe7.mp4

Is there any workaround for this?

**Comment by antony-jr** [comment]
This is a issue with X11. This is a bug, needs to be fixed. But it's a bit tricky. I will fix this asap.

**Comment by antony-jr** [comment]
This actually happened to me sometimes, but it seems it occurs all the time in i3.

**Comment by antony-jr** [comment]
@namelivia Can you try the dev version from the official site and see if it solves the issue?

**Comment by namelivia** [comment]
> @namelivia Can you try the dev version from the official site and see if it solves the issue?

I would say it is fixed for me :hearts: 
Thanks!

**Comment by antony-jr** [comment]
Great, this issue is a bit hard to reproduce but if it happens again please feel free to reopen this.
